### ISSUE TITLE
Add Docs icon navbar item and link to online docs URL

### ISSUE THREAD

**Issue by parkview** [madeinoz67/maker-hub#60]
- [ ] Add new 'Docs' navbar item linking to online documents <https://madeinoz67.github.io/maker-hub/> 
- [ ] update 'Help' navbar icon to link to github discussions <https://github.com/madeinoz67/maker-hub/discussions>

**Comment by mohitbalwani** [comment]
Hey I would like to work on this issue !
I am pretty new to this so how do you want me to contribute?

**Comment by madeinoz67** [comment]
awesome @mohitbalwani a PR will be fine.

I've been pushing quite a few changes so just make sure you keep you your master synced.   

As per our CONTIBUTION doc, branch from your fork master and dev on there

**Comment by madeinoz67** [comment]
with this current issue, I think it be a icon on the navbar called docs and then link to the current online docs 

also see issue #75 if you're feeling adventurous

**Comment by madeinoz67** [comment]
Just realised that the route '/docs' will clash with api openapi generated docs, so will need to make the static route something other than /docs 

Maybe the navbar icon will route to /documentation page that lists all documentation both openapi docs and projects github mkdocs site

**Comment by jubbp** [comment]
Any movement on this issue? Can I assist?
